// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LiveHint",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "LiveHint",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .running),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .speechRecognition(purposeString: "Spracherkennung wird verwendet, um live Vorschläge anzuzeigen."),
                .microphone(purposeString: "Das Mikrofon wird verwendet, um deine Stimme aufzuzeichnen."),
                .appTransportSecurity(configuration: .init(
                    exceptionDomains: [
                        .init(
                            domainName: "127.0.0.1",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        ),
                        .init(
                            domainName: "192.168.211.60",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        )
                    ]
                )),
                .localNetwork(purposeString: "The server may be on the local network"),
                .outgoingNetworkConnections()
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Cay-Zhang/SwiftSpeech", "0.9.3"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftSpeech", package: "SwiftSpeech")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
